version: "3.9"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dcbpp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  spring-api:
    restart: always
    build: .
    ports:
      - 8081:8080
    environment:
      DB_HOST: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    links:
      - mysqldb
volumes:
  mysql-data:

